name: Process New Event

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Important for "Create Pull Request" step

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use the specific Node.js version your script requires

      - name: Install dependencies
        run: yarn install --network-timeout 1000000

      - name: Build Project
        run: yarn build

      - name: Process new event
        run: yarn start

      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push
        run: |
          git checkout -b new-summary
          git add summaries/*
          git commit -m "Add new summary"
          git push origin new-summary
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Add new summary'
          body: 'This pull request adds a new summary.'
          branch: 'new-summary'
